version: '3.7'

services:
    app:
     build: ./php
     container_name: app
     volumes:
       - ./src:/var/www/html
     depends_on:
       - db
    db:
     image: mysql:5.7.22
     command: --innodb-use-native-aio=0
     restart: always
     ports:
       - "3306:3306"
     volumes:
       - "./data:/var/lib/mysql"
     environment:
       - MYSQL_DATABASE=app
       - MYSQL_ROOT_PASSWORD=root

    nginx:
     build: ./nginx
     restart: always
     ports:
       - "80:80"
     volumes:
       - "./src:/var/www/html"
     depends_on:
       - app
     environment:
       VIRTUAL_HOST: app.local
